from project.settings.base import BASE_DIR, SECRET_KEY
import datetime


# CORS SETTINGS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000", # :TODO DELETE
    "http://127.0.0.1:3000", # :TODO DELETE
]

# MORE SECURITIES
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_BROWSER_XSS_FILTER = True
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')